# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-24 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20170523_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='business',
            new_name='business_line',
        ),
    ]
