# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_auto_20170525_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='user',
            field=models.ManyToManyField(to='hosts.UserInfo'),
        ),
    ]
